version: "3.7"
services:
  proxy-storage:
    image: peavers:proxy-storage:latest
    container_name: proxy-storage
    restart: unless-stopped
    depends_on:
      - proxy-mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=proxy-mongo
    ports:
      - 8080:8080

  proxy-mongo:
    image: mongo:latest
    container_name: proxy-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - proxy-mongo-data:/data/db

volumes:
  proxy-mongo-data:
